import keyMirror from 'keymirror';

export default keyMirror({
  LICENSE_LOAD: null,
  LICENSE_LOAD_SUCCESS: null,
  LICENSE_LOAD_FAILED: null,

  CLOUD_AUTHENTICATION_START: null,
  CLOUD_AUTHENTICATION_SUCCESS: null,
  CLOUD_AUTHENTICATION_FAILED: null,

  CLOUD_AUTHENTICATION_LOG_LOAD: null,
  CLOUD_AUTHENTICATION_LOG_LOAD_SUCCESS: null,
  CLOUD_AUTHENTICATION_LOG_LOAD_FAILED: null,

  CLOUD_AUTHENTICATION_LOG_PARAMS_SET: null,

  CLOUD_AUTHENTICATION_STATUS: null,
  CLOUD_AUTHENTICATION_STATUS_SUCCESS: null,
  CLOUD_AUTHENTICATION_STATUS_FAILED: null,
});
